version: 2.1
jobs:
    lint-php:
        docker:
            - image: cimg/php:8.2-node
        steps:
            - checkout
            - run:
                  name: Install production dependencies
                  command: composer install --no-dev -o
            - run:
                  name: Composer validate
                  command: composer validate --strict
            - run:
                  name: Normalize composer.json
                  command: composer normalize --no-interaction --dry-run
            - run:
                  name: Check if NewsUK and NewsPress PHPCS standards are installed
                  command: |
                    phpcsStandards=$(vendor/bin/phpcs -i)
                    echo $phpcsStandards
                    if echo $phpcsStandards | grep -q "NewsUK" && echo $phpcsStandards | grep -q "NewsPress"; then
                      echo "NewsUK and NewsPress PHPCS standards are installed successfully."
                    else
                      echo "Error: NewsUK and NewsPress PHPCS standards are not installed."
                      exit 1
                    fi
            - persist_to_workspace:
                  root: .
                  paths:
                      - vendor
workflows:
    version: 2
    build:
        jobs:
            - lint-php
