version: 2.1
jobs:
    build-php:
        docker:
            - image: cimg/php:8.2-node
        steps:
            - checkout
            - run:
                  name: Install Composer
                  command: |
                      curl -s https://getcomposer.org/installer | php
                      mv composer.phar /usr/local/bin/composer
            - run:
                  name: Install production dependencies
                  command: composer install --no-dev -o
            - run:
                  name: Composer validate
                  command: composer validate --strict
            - run:
                  name: List installed phpcs standards
                  command: vendor/bin/phpcs -i
            - run:
                  name: Check if NewsUK standard is installed
                  command: |
                    if vendor/bin/phpcs -i | grep -q "NewsUK"; then
                      echo "NewsUK PHPCS standard is installed successfully."
                    else
                      echo "Error: NewsUK PHPCS standard is not installed."
                      exit 1
                    fi
            - persist_to_workspace:
                  root: .
                  paths:
                      - vendor
workflows:
    version: 2
    build:
        jobs:
            - build-php
